server:
  port: 8081

spring:
  application:
    name: cocktail-list
  
  datasource:
    url: jdbc:mysql://localhost:3306/cocktails
    username: cocktail_user
    password: cocktail_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # Usa solo jwk-set-uri senza issuer-uri per accettare token da localhost E keycloak
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}/realms/cocktail-realm/protocol/openid-connect/certs

keycloak:
  realm: cocktail-realm
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}
  resource: cocktail-client
  public-client: true

# Springdoc OpenAPI / Swagger UI
springdoc:
  swagger-ui:
    oauth:
      client-id: cocktail-client
      use-pkce-with-authorization-code-grant: false
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  
logging:
  level:
    org.springframework.security: DEBUG
    org.keycloak: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/cocktails
    username: cocktail_user
    password: cocktail_pass
  security:
    oauth2:
      resourceserver:
        jwt:
          # Usa solo jwk-set-uri per validare la firma, accetta token da localhost (browser) e keycloak (Docker)
          jwk-set-uri: http://keycloak:8080/realms/cocktail-realm/protocol/openid-connect/certs

keycloak:
  auth-server-url: http://keycloak:8080
